#!/usr/bin/env python3
"""Embed testdata/descriptors/*.bin as Mojo helpers (no runtime file I/O)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests" / "descriptor_blobs.mojo"
BLOBS = [
    ("benchmark_v2_fds", ROOT / "testdata/descriptors/benchmark_v2.bin"),
    ("import_parent_fds", ROOT / "testdata/descriptors/import_parent.bin"),
    ("legacy_proto2_fds", ROOT / "testdata/descriptors/legacy_proto2.bin"),
]


def emit_fn(name: str, data: bytes) -> str:
    hexes = ", ".join(f"0x{b:02x}" for b in data)
    return (
        f"def {name}() -> List[Byte]:\n"
        f"    return bytes_of({hexes})\n"
    )


def main() -> int:
    parts = [
        '"""Generated by scripts/embed_descriptors.py. Do not edit by hand."""\n',
        "from std.collections import List\n",
        "from bytes_util import bytes_of\n\n",
    ]
    for name, path in BLOBS:
        parts.append(emit_fn(name, path.read_bytes()))
        parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
